### ISSUE TITLE
Save our Ship 2 Compability

### ISSUE THREAD

**Issue by chill0r** [cabmoomoo/Rimworld-MiscRobotsPlusPlus#2]
When playing with Save our Ship 2 the robots get damage in vacuum.
To prevent that the stats 
```
<HypoxiaResistance>1</HypoxiaResistance>
<DecompressionResistance>1</DecompressionResistance>
```
should be added to the robot base.

**Comment by chill0r** [comment]
Seems to be a bug in sos2 not here atm ;) sorry for the inconvenience

**Comment by cabmoomoo** [comment]
The base mod Misc Robots has added the required stats to the robots, so the incompatibility shouldn't be on this end.
I do not know if something has changed with sos2 to cause a new bug, but one we have encountered before has to do with having sos2 installed both locally and through the Steam Workshop. There is a known and unpatched bug in Rimworld that causes the Steam version of a mod to have it's name changed when a local version is found which screws up compatibility stuff. You can read a bit more on the [Rimworld Wiki](https://rimworldwiki.com/wiki/Modding_Tutorials/MayRequire#Exceptions) at the bottom of the linked page. If you have multiple versions of sos2 installed, try unsubscribing and deleting all but the one you want to use.
