### ISSUE TITLE
Save Our Ship 2 Compatibility

### ISSUE THREAD

**Issue by Beyer-J** [cabmoomoo/Rimworld-MiscRobotsPlusPlus#3]
Robots suffer from Hypoxia and Decompression in Space.

This isn't exactly a bug, but it makes sense to not have them die this way.

**Comment by cabmoomoo** [comment]
This has been reported a couple of times before on the Steam page. I stumbled upon this solution and so far it's helped everyone.

> Do you have a version of SOS2 installed locally? With some experimentation I've been able to confirm there is (still) a bug with Rimworld itself when a Workshop and Local mod have the same packageId. The [wiki modding tutorials page](https://rimworldwiki.com/wiki/Modding_Tutorials/MayRequire#Exceptions) makes note of this bug (last item in the Exceptions section). You can test this by moving (or deleting) the local mod and seeing if the Workshop version now works as expected.
Compatibility with SOS2 is handled by the parent mod and seems to be fully functional. If this case does not apply to you, let me know so I can investigate further.

**Comment by Beyer-J** [comment]
That seems to have done it. Thank you.
